#version: "3.9"

services:
  db:
    image: mysql:8.0.14
    container_name: bmsys_db
    tty: true
    restart: always
    ports:
      - "33308:3306"
    volumes:
      - ./db/${MYSQL_INIT}:/docker-entrypoint-initdb.d
      - ./db/mysql_data:/var/lib/mysql
      - ./db/mysql_log:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Tokyo
  app:
    build: ./app
    container_name: bmsys_app
    tty: true
    restart: always
    depends_on:
      - db
    volumes:
      - ./app:/var/www
      - ./api/.env.${PROFILE}:/var/www/laravel/.env
      # - laravel_framework_volume:/var/www/laravel/storage/framework
      # - laravel_vendor_volume:/var/www/laravel/vendor
      # - laravel_node_modules_volume:/var/www/laravel/node_modules
    ports:
      - "18085:8000"
  web:
    container_name: bmsys_web
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - 8082:80
    tty: true
    restart: always
    depends_on:
      - app
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  flyway:
    container_name: bmsys_flyway
    build: ./flyway
    tty: true
    restart: always
    command: /bin/bash
    image: flyway/flyway
    depends_on:
      - db
    volumes:
      - ./flyway/sql:/flyway/sql
      - ./flyway/conf/${FLYWAY_CONF}:/flyway/conf/flyway.conf
      - ./flyway/drivers:/flyway/drivers
# volumes:
# laravel_framework_volume:
# laravel_vendor_volume:
# laravel_node_modules_volume:
